// Generated by dts-bundle-generator v9.5.1

import { Swear } from 'swear';

declare const _default: (command: string, buffer?: number) => Swear<string>;

export {
	_default as default,
};

export {};
